export const GAME_CONSTANTS = {
  SLOTS_PER_ROW: 3,
  ROWS_PER_PLAYER: 2,
  ACTIONS_PER_TURN: 3,
  HAND_SIZE_CAP: 5,
  ENERGY_STARTING_MAX: 2,
  ENERGY_GROWTH_PER_TURN: 1,
  ENERGY_CAP: 6,
  CHARGE_BASELINE_PER_TURN: 1,
  MOVEMENT_ACTION_COST: 1,
  MOVEMENT_ENERGY_COST: 0,
  ATTACK_ACTION_COST: 1,
  ATTACK_ENERGY_COST: 0,
} as const;
